export {
  COMPARISON_ASPECTS,
  COMPATIBILITY_LEVELS,
  DEVICE_VOLTAGE_PROFILES,
  PLUG_TYPES,
} from "@/types/constants";
export type {
  ComparisonAspect,
  AdapterStatus,
  BaseComparisonFinding,
  ComparisonFinding,
  ComparisonFormValues,
  ComparisonResult,
  CompatibilityLevel,
  Country,
  DeviceProfile,
  DeviceComparison,
  DeviceVoltageProfile,
  FrequencyComparison,
  FrequencyStatus,
  Plug,
  PlugComparison,
  PlugType,
  VoltageComparison,
  VoltageStatus,
} from "@/types/domain";
